// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sircip.Server.Data;

#nullable disable

namespace Sircip.Server.Data.Migrations
{
    [DbContext(typeof(SircipDbContext))]
    partial class SircipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sircip.Server.Authentication.Models.Sesion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CerradaUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("RolAlEmitir")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)")
                        .IsFixedLength();

                    b.Property<DateTime>("UltimaActividadUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Sesiones", (string)null);
                });

            modelBuilder.Entity("Sircip.Server.Authentication.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte>("Rol")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Usuarios_Rol", "[Rol] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("Sircip.Server.Padron.Models.Importacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BajaUsuarioId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BajaUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("CantidadRegistros")
                        .HasColumnType("int");

                    b.Property<string>("DetalleError")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaImportacionUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("Periodo")
                        .HasColumnType("int");

                    b.Property<byte>("Resultado")
                        .HasColumnType("tinyint");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BajaUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Periodo", "Resultado", "BajaUtc");

                    b.ToTable("Importaciones", null, t =>
                        {
                            t.HasCheckConstraint("CK_Importaciones_Resultado", "[Resultado] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("Sircip.Server.Authentication.Models.Sesion", b =>
                {
                    b.HasOne("Sircip.Server.Authentication.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sircip.Server.Padron.Models.Importacion", b =>
                {
                    b.HasOne("Sircip.Server.Authentication.Models.Usuario", "BajaUsuario")
                        .WithMany()
                        .HasForeignKey("BajaUsuarioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Sircip.Server.Authentication.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BajaUsuario");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
